name: Docker Image Build e Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag adenilsonkon/api-python:latest
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      # Step 4: Run Trivy to scan the Docker image for vulnerabilities
    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: adenilsonkon/api-python:latest
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
    - name: Push the Docker image
      run: docker push adenilsonkon/api-python:latest
